= Guideline for writing tests regarding admin features and clean-up

== Prerequisites

You obviously need to have admin rights on the test environment. So environment needs to have `admin_cli` configuration option set.

This will make possible calls to `Environment#admin` and `Environment#admin_cli_executor` methods. These methods give access to doing operations as a cluster admin user. See `ClusterAdmin` and `AdminCliExecutor` classes.

== What's the issue?

Regular clean-up between scenarios consists of removing all user owned projects. This is enough as long as no configuration changes to environment is done and users did not obtain additional privileges during scenario.

If configuration changes happened though, these can affect later scenarios execution and lead to false positives/negatives.

== The solution

For visibility, please tag any scenarios using admin with the `@admin` tag.

To avoid such situation we have to define clean-up routines. Clean-up routines can be defined either directly in step code by calling `teardown_add { proc.. }` or by registering clean-up steps from wihtin scenario.

These clean-up steps will execute after scenario no matter if scenario succeeded or not. So you don't have to revert the changes in clean-up and regular steps.

Another thing to note is that if these clean-up steps fail (raise a ruby error), cucumber execution will stop. That means no further scenarios will be run.

Design your clean-up in a way that it fails only if further scenario execution could be negatively affected if clean-up is not successful. For example failing to remove some random project should not make whole cucumber fail (this is unlikely to affect anything). But a user with wrong permissions should cause cucumber to quit so that user can manually recover user or use another user.

== Example

=== defining clean-up steps in scenario text

See `features/test/clean_up.feature`.

Note that upon execution, any dynamic code in steps is resolved so clean-up steps usually don't need special method and variable handling. You just need to ensure operations are well specified. For example if you want to remove a project at the end, specify its name in the step. Dont leave it just `the project`. Otherwise `the project` at teardown might be a completely different project. Same goes to users and any other resources we work with.

=== clean-up defined in step code
One admin scenario is "Admin could get/edit/delete the project" defined inside `features/admin/project.feature`. It creates a project as admin but at that point we don't have guarantee user will receive admin rights over it and will be able to remove it.

So here we look at the step definition of `admin creates a project`. It is inside `features/step_definitions/project.rb`. What step does is insert following code in the beginning:

     _project = project # we need variable for the teardown proc
     teardown_add { @result = _project.delete(by: :admin) }

Basically it adds up one more clean-up routine to the teardown sequence. As you see result of the operation is never checked because even if it fails, then likelihood of breaking other scenarios is minimal. So we don't want everything to break.

One detail to think about is the variables use within these clean-up routines. Make sure you understand how procs and lambdas work in Ruby. Basically they resolve variables at the time they are called in the context (or with the binding) they were created in/with.

In this case, if we skip doing `_project = project` and just use `project` inside the proc, then the `#project` method will be called at the time of teardown and it may resolve to any other project, not necessarily what we created with the step call. Using the `_project` variable ensures we try to delete the exact same project that we created as admin. No matter how many times we call the step, it will register a proper clean-up.

As another example, see the step `Given /^(the [a-z]+) user is cluster-admin$/` in `features/step_definitions/policy.rb`:

    _admin = admin
    teardown_add {
      res = _admin.cli_exec(
        :oadm_policy,
        policy_type: "remove-cluster-role-from-user",
        role_name: "cluster-admin",
        user_name: user_name
      )
      raise "could not restore user #{user_name}" unless res[:success]
    }

Here we fail whole run if user cannot be restored for any reason.
